### ISSUE TITLE
Application to other domains e.g. radar signal processing

### ISSUE THREAD

**Issue by saveriogzz** [spotify/pedalboard#23]
Thanks @psobot and Spotify for this great library!

I have lately been thinking about some other application of this great work and would like to ask the community some suggestions.

Just a little bit of background:
I work as a data engineer for a project in climate science, where we have instruments such as Frequency-Modulated Continuous Wave Radars ([FMCW](https://www.radartutorial.eu/02.basics/Frequency%20Modulated%20Continuous%20Wave%20Radar.en.html)) or [Microwave Radiometers](https://en.wikipedia.org/wiki/Microwave_radiometer). They produce data in (or converted into) a popular format in climate science, called [NetCDF](https://en.wikipedia.org/wiki/NetCDF).  NetCDF are files composed by [multidimensional arrays](https://github.com/pydata/xarray#why-xarray).  
An increasingly popular way of analyzing this type of data is using the great library [Xarray](https://github.com/pydata/xarray).

My question is: could we use pedalboard for e.g. finding new ways of reducing the noise from these type of data?

Thanks

**Comment by drubinstein** [comment]
Interesting idea. Although I think applying RF signal processing to Pedalboard would technically work, I'm not sure it's the best idea to mix RF signals with a library designed around audio signal processing (which is often done at a sample rates multiple orders of magnitude less from my experience). For example, would you intend to implement an [ambiguity function](https://en.wikipedia.org/wiki/Ambiguity_function) as a VST and then use it with Pedalboard? There are already libraries designed around RF data such as [GNURadio](https://en.wikipedia.org/wiki/GNU_Radio) and [PyRAPID](http://radar.alizadeh.ca/) that will most likely fit your use case better.

**Comment by saveriogzz** [comment]
Thanks for the feedback @drubinstein !
Yes I was actually thinking to create one or more plugins within Pedalboard to be used for this scope but you are probably right.

I will keep this issue open atm but maintainers please feel free to close it if found appropriate!
